### ISSUE TITLE
connection request  rejected

### ISSUE THREAD

**Issue by q1121599315** [Coding-with-Adam/Dash-by-Plotly#12]
Dear Charming Data,I am a newbee of plotly-dash , when i build a sever by "app.run_server(debug=True)",and then open the link,my request was denied .  and if i turn the 'debug' option as False ,  comes the following error:
Traceback (most recent call last):
  File "D:\BaiduNetdiskDownload\BeforeAfter\before-after.py", line 45, in <module>
    app.run_server()
  File "D:\Program Files\Python36\lib\site-packages\dash\dash.py", line 2033, in run_server
    self.server.run(host=host, port=port, debug=debug, **flask_run_options)
  File "D:\Program Files\Python36\lib\site-packages\flask\app.py", line 922, in run
    run_simple(t.cast(str, host), port, self, **options)
  File "D:\Program Files\Python36\lib\site-packages\werkzeug\serving.py", line 1008, in run_simple
    inner()
  File "D:\Program Files\Python36\lib\site-packages\werkzeug\serving.py", line 957, in inner
    fd=fd,
  File "D:\Program Files\Python36\lib\site-packages\werkzeug\serving.py", line 781, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "D:\Program Files\Python36\lib\site-packages\werkzeug\serving.py", line 686, in __init__
    super().__init__(server_address, handler)  # type: ignore
  File "D:\Program Files\Python36\lib\socketserver.py", line 456, in __init__
    self.server_bind()
  File "D:\Program Files\Python36\lib\http\server.py", line 138, in server_bind
    self.server_name = socket.getfqdn(host)
  File "D:\Program Files\Python36\lib\socket.py", line 673, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 0: invalid start byte

**Comment by Coding-with-Adam** [comment]
Hi,It looks like your problem is with the data. It has to be converted to utf-8 format.

Adam SchroederOwnerCharming Data LLC 118 E 124th ST #1808, New York, New York 10035   My Pronouns: He, him, his ¡Hablo español! 
            
            
            
            
                
                    On Wed, Sep 15, 2021, 06:07 am q1121599315 ***@***.***> wrote:
                    
                
                
                    
Dear Charming Data,I am a newbee of plotly-dash , when i build a sever by "app.run_server(debug=True)",and then open the link,my request was denied .  and if i turn the 'debug' option as False ,  comes the following error:
Traceback (most recent call last):
File "D:\BaiduNetdiskDownload\BeforeAfter\before-after.py", line 45, in 
app.run_server()
File "D:\Program Files\Python36\lib\site-packages\dash\dash.py", line 2033, in run_server
self.server.run(host=host, port=port, debug=debug, **flask_run_options)
File "D:\Program Files\Python36\lib\site-packages\flask\app.py", line 922, in run
run_simple(t.cast(str, host), port, self, **options)
File "D:\Program Files\Python36\lib\site-packages\werkzeug\serving.py", line 1008, in run_simple
inner()
File "D:\Program Files\Python36\lib\site-packages\werkzeug\serving.py", line 957, in inner
fd=fd,
File "D:\Program Files\Python36\lib\site-packages\werkzeug\serving.py", line 781, in make_server
host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
File "D:\Program Files\Python36\lib\site-packages\werkzeug\serving.py", line 686, in init
super().init(server_address, handler)  # type: ignore
File "D:\Program Files\Python36\lib\socketserver.py", line 456, in init
self.server_bind()
File "D:\Program Files\Python36\lib\http\server.py", line 138, in server_bind
self.server_name = socket.getfqdn(host)
File "D:\Program Files\Python36\lib\socket.py", line 673, in getfqdn
hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 0: invalid start byte

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Coding-with-Adam/Dash-by-Plotly/issues/12",
"url": "https://github.com/Coding-with-Adam/Dash-by-Plotly/issues/12",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by q1121599315** [comment]
> Hi,It looks like your problem is with the data. It has to be converted to utf-8 format. Adam SchroederOwnerCharming Data LLC 118 E 124th ST #1808, New York, New York 10035   My Pronouns: He, him, his ¡Hablo español!  On Wed, Sep 15, 2021, 06:07 am q1121599315 ***@***.***> wrote: Dear Charming Data,I am a newbee of plotly-dash , when i build a sever by "app.run_server(debug=True)",and then open the link,my request was denied . and if i turn the 'debug' option as False , comes the following error: Traceback (most recent call last): File "D:\BaiduNetdiskDownload\BeforeAfter\before-after.py", line 45, in app.run_server() File "D:\Program Files\Python36\lib\site-packages\dash\dash.py", line 2033, in run_server self.server.run(host=host, port=port, debug=debug, **flask_run_options) File "D:\Program Files\Python36\lib\site-packages\flask\app.py", line 922, in run run_simple(t.cast(str, host), port, self, **options) File "D:\Program Files\Python36\lib\site-packages\werkzeug\serving.py", line 1008, in run_simple inner() File "D:\Program Files\Python36\lib\site-packages\werkzeug\serving.py", line 957, in inner fd=fd, File "D:\Program Files\Python36\lib\site-packages\werkzeug\serving.py", line 781, in make_server host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd File "D:\Program Files\Python36\lib\site-packages\werkzeug\serving.py", line 686, in init super().init(server_address, handler) # type: ignore File "D:\Program Files\Python36\lib\socketserver.py", line 456, in init self.server_bind() File "D:\Program Files\Python36\lib\http\server.py", line 138, in server_bind self.server_name = socket.getfqdn(host) File "D:\Program Files\Python36\lib\socket.py", line 673, in getfqdn hostname, aliases, ipaddrs = gethostbyaddr(name) UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 0: invalid start byte —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. [ { ***@***.***": "http://schema.org", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "#12", "url": "#12", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

Thank you ！ I reinstalled python and checked the Debug option and the problem is fixed.
