### ISSUE TITLE
AttributeError: FormGroup was deprecated

### ISSUE THREAD

**Issue by schwabts** [Coding-with-Adam/Dash-by-Plotly#32]
What should I do about this?

Dash-by-Plotly-Coding-with-Adam/Bootstrap/bootstrap_modal.py:4: UserWarning: 
The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`
  import dash_core_components as dcc
Traceback (most recent call last):
  File "Dash-by-Plotly-Coding-with-Adam/Bootstrap/bootstrap_modal.py", line 22, in <module>
    dbc.FormGroup(
  File "Dash-by-Plotly-Coding-with-Adam\Bootstrap\.venv\lib\site-packages\dash_bootstrap_components\__init__.py", line 51, in __getattr__
    raise AttributeError(
AttributeError: FormGroup was deprecated in dash-bootstrap-components version 1.0.0. You are using 1.2.1.

**Comment by Coding-with-Adam** [comment]
Thanks for the heads up @schwabts. Did you solve the `dcc` issue? you need to do `from dash import dcc`./

I wish I had the time up update all these older files.
